### PR TITLE
Sort classNames when comparing them, since order of classNames does n…

### PR DESCRIPTION
**Pull request by kmudrick**
…ot matter with css specificity

### CODE REVIEW

**Comment by TimothyRHuertas** [comment]
Thanks.  Ill get it merged, bump the version and republish the module.

**Comment by TimothyRHuertas** [comment]
Humm for some reason npm publish is not respecting the version in the package.json file.  @sprjr can you try to publish it?

**Comment by whichsteveyp** [comment]
Interesting, I pulled things down and saw `5.0.0` in the package.json and was able to publish fine. Wonder what that's about... @kmudrick it's showing up on the registry for me now.

**Comment by whichsteveyp** [comment]
Although, it looks like we jumped (or didn't publish?) `4.0.0`?

**Comment by TimothyRHuertas** [comment]
5.0 was me trying 2x out of desperation.

**Pull request merged**
